language: python
python: 2.7
install: make travis
script: make test
notifications:
  email: plone.intranet@netsight.co.uk
  irc: "chat.freenode.net#plone.intranet"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
